name: Test Install Poetry Action # Related to https://github.com/snok/install-poetry/issues/94

on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        python-version: [ '3.7', '3.8', '3.10', '3.11' ]
        poetry-version: [ '1.1.10', '1.1.14', '1.2.1', '1.2.2' ]
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install and configure Poetry version ${{ matrix.poetry-version }}
        uses: GuillaumeFalourd/install-poetry@main
        with:
          version: ${{ matrix.poetry-version }}
          virtualenvs-create: false
